variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - prepare
  - build

prepare-docker:
  stage: prepare
  image: docker
  script:
    - echo "Hello"
    - docker ps -a
    - docker images
    - echo "Hello"

build-docker:
  stage: build
  image: docker
  script:
    - echo "Hello"
    - docker build -t babishan/webservice:1.0 webservice
    - docker build -t babishan/management:1.0 management
    - echo "Hello"

#image: docker:dind
#
#variables:
#  JAVA_HOME: /usr/lib/jvm/default-java-11-openjdk
#  DOCKER_HOST: "unix:///var/run/docker.sock"
#
#stages:
#  - clean
#  - build
#  - deploy
#
#clean:
#  stage: clean
#  before_script:
#    - apk update
#    - apk add openjdk11-jre-headless
#    - apk add docker-compose
#  script:
#    - docker-compose down -v --rmi all --remove-orphans
#    - ./mvnw clean
#  only:
#    - master
#
#build:
#  stage: build
#  before_script:
#    - apk update
#    - apk add openjdk11-jre-headless
#    - apk add docker-compose
#  script:
#    - ./mvnw package
#    - docker-compose build
#  only:
#    - master
#
#deploy:
#  stage: deploy
#  before_script:
#    - apk update
#    - apk add openjdk11-jre-headless
#    - apk add docker-compose
#  script:
#    - docker-compose up
#  only:
#    - master
#  when: manual
