image: ubuntu:16.04

variables:
  JAVA_HOME: /usr/lib/jvm/default-java

stages:
  - prepare
  - clean
  - build
  - deploy

preapare:
  stage: prepare
  script:
    - apt update
    - apt install git -y
    - apt install default-jdk -y
    - apt install docker -y
    - apt install docker-compose -y
  only:
    - master

clean:
  stage: clean
  script:
    - ./mvnw clean
  only:
    - master

build:
  stage: build
  script:
    - ./mvnw package
    - docker-compose build
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker-compose up
  only:
    - master
  when: manual
