image: creatiwww/docker-compose:latest

services:
  - docker:dind
  -
variables:
  JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - ./mvnw clean package
    - docker-compose build
  only:
    - master

deploy:
  stage: build
  script:
    - docker-compose up
  only:
    - master
  when: manual
