variables:
  JAVA_HOME: /usr/lib/jvm/open-jdk

stages:
  - clean
  - build
  - deploy

clean:
  stage: clean
  script:
    - ./mvnw clean
  only:
    - master

build:
  stage: build
  script:
    - ./mvnw package
    - docker-compose build
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker-compose up
  only:
    - master
  when: manual
