variables:
  JAVA_HOME: /usr/lib/jvm/default-java
  PROJECT_DIR: $CI_PROJECT_DIR
  ANSIBLE_DIR: $CI_PROJECT_DIR/ansible
stages:
  - prepare
  - build

prepare-ansible:
  stage: prepare
  before_script:
    - ansible --version
    - env
  script:
    - echo "Hello"
    - docker ps -a
    - docker images
    - echo "Hello"

build-using-ansible:
  stage: build
  before_script:
    - ansible-galaxy collection install community.docker
    - ansible-playbook ansible/create_docker_network.yml
  script:
    - ansible-playbook ansible/build_docker_images.yml
#
#stages:
#  - clean
#  - build
#  - deploy
#
#clean:
#  stage: clean
#  before_script:
#    - apk update
#    - apk add openjdk11-jre-headless
#    - apk add docker-compose
#  script:
#    - docker-compose down -v --rmi all --remove-orphans
#    - ./mvnw clean
#  only:
#    - master
#
#build:
#  stage: build
#  before_script:
#    - apk update
#    - apk add openjdk11-jre-headless
#    - apk add docker-compose
#  script:
#    - ./mvnw package
#    - docker-compose build
#  only:
#    - master
#
#deploy:
#  stage: deploy
#  before_script:
#    - apk update
#    - apk add openjdk11-jre-headless
#    - apk add docker-compose
#  script:
#    - docker-compose up
#  only:
#    - master
#  when: manual