image: debian:latest

variables:
  JAVA_HOME: /usr/lib/jvm/default-java
  DOCKER_HOST: "unix:///var/run/docker.sock"

stages:
  - clean
  - build
  - deploy

clean:
  stage: clean
  before_script:
    - apt update
    - apt install default-jre-headless -y
    - apt install docker docker-compose -y
    - service docker start
  script:
    - docker-compose down -v --rmi all --remove-orphans
    - ./mvnw clean
  only:
    - master

build:
  stage: build
  before_script:
    - apt update
    - apt install default-jre-headless -y
    - apt install docker docker-compose -y
    - service docker start
  script:
    - ./mvnw package
    - docker-compose build
  only:
    - master

deploy:
  stage: deploy
  before_script:
    - apt update
    - apt install default-jre-headless -y
    - apt install docker docker-compose -y
    - service docker start
  script:
    - docker-compose up
  only:
    - master
  when: manual
