image: ubuntu:16.04

variables:
  JAVA_HOME: /usr/lib/jvm/open-jdk

stages:
  - prepare
  - clean
  - build
  - deploy

preapare:
  stage: prepare
  script:
    - src/main/scripts/datasnapshot_install_ubuntu-1604.sh
  only:
    - master

clean:
  stage: clean
  script:
    - ./mvnw clean
  only:
    - master

build:
  stage: build
  script:
    - ./mvnw package
    - docker-compose build
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker-compose up
  only:
    - master
  when: manual
