image: ubuntu:latest

variables:
  JAVA_HOME: /usr/lib/jvm/default-java
  DOCKER_HOST: ec2-18-192-63-128.eu-central-1.compute.amazonaws.com

stages:
  - clean
  - build
  - deploy

clean:
  stage: clean
  before_script:
    - apt update
    - apt install default-jdk -y
    - apt install docker -y
    - apt install docker-compose -y
  script:
    - docker-compose down -v --rmi all --remove-orphans
    - ./mvnw clean
  only:
    - master

build:
  stage: build
  before_script:
    - apt update
    - apt install default-jdk -y
    - apt install docker -y
    - apt install docker-compose -y
  script:
    - ./mvnw package
    - docker-compose build
  only:
    - master

deploy:
  stage: deploy
  before_script:
    - apt update
    - apt install default-jdk -y
    - apt install docker -y
    - apt install docker-compose -y
  script:
    - docker-compose up
  only:
    - master
  when: manual
