image: alpine:latest

variables:
  JAVA_HOME: /usr/lib/jvm/default-jvm
#  DOCKER_HOST:

stages:
  - clean
  - build
  - deploy

clean:
  stage: clean
  before_script:
    - apk update
    - apk upgrade
    - apk add openjdk11-jre-headless
    - apk add docker-compose
  script:
    - docker-compose down -v --rmi all --remove-orphans
    - ./mvnw clean
  only:
    - master

build:
  stage: build
  before_script:
    - apk update
    - apk upgrade
    - apk add openjdk11-jre-headless
    - apk add docker-compose
  script:
    - ./mvnw package
    - docker-compose build
  only:
    - master

deploy:
  stage: deploy
  before_script:
    - apk update
    - apk upgrade
    - apk add openjdk11-jre-headless
    - apk add docker-compose
  script:
    - docker-compose up
  only:
    - master
  when: manual
