#version: "3.9"

networks:
  default:
    external:
      name: datasnapshot

#volumes:
#  workspace:

services:
  database:
    image: postgres
    hostname: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: datasnapshot
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
  management:
    build: management
    hostname: eureka
#    image: babishan/management:1.0
    ports:
      - "8761:8761"
    restart: always
  prod:
    build: webservice
    hostname: prodservice
#    image: babishan/webservice:1.0
    ports:
       - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: always
  dev:
    build: webservice
    hostname: devservice
    #    image: babishan/webservice:1.0
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    restart: always
