server:
  port: 8080
spring:
  application:
    name: datasnapshot-dev
  h2:
    console:
      enabled: true
      path: /h2
      #settings:
        #trace: true
        #web-allow-others: true
  datasource:
    url: jdbc:h2:./data/db
    username: sa
    #initialization-mode: always can be used when we have data.sql and schema.sql .By default it wll be picked only in embedded database
    password: password
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: info, health, shutdown, prometheus
  endpoint:
    shutdown:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true