server:
  port: 8080
spring:
  application:
    name: datasnapshot-prod
  datasource:
    url: jdbc:mysql://eu-database.cu33wsc16bjs.eu-central-1.rds.amazonaws.com:3306/datasnapshot
    username: admin
    #initialization-mode: always can be used when we have data.sql and schema.sql .By default it wll be picked only in embedded database
    password: adminpass
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        show_sql: false
    hibernate:
      ddl-auto: update
    show-sql: false
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: info, health, shutdown, prometheus
  endpoint:
    shutdown:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true