server:
  port: 8080
spring:
  application:
    name: datasnapshot-prod
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    #initialization-mode: always can be used when we have data.sql and schema.sql .By default it wll be picked only in embedded database
    password: rootpassword
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: false
        show_sql: false
    hibernate:
      ddl-auto: update
    show-sql: false
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: info, health, shutdown, prometheus
  endpoint:
    shutdown:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka}
  instance:
    preferIpAddress: true