CREATE TABLE RECON_DATA (
    PRIMARY_KEY  VARCHAR(128)  NOT NULL,
    NAME VARCHAR(128),
    DESCRIPTION VARCHAR(128),
    UPDATED_TIMESTAMP TIMESTAMP,
    PRIMARY KEY (PRIMARY_KEY)
);

CREATE TABLE CORRUPT_DATA (
    GENERATED_PRIMARY_KEY INTEGER NOT NULL,
    REASON VARCHAR(128),
    RAW_DATA CLOB,
    PRIMARY KEY (GENERATED_PRIMARY_KEY)
);
