- name: Build docker images
  hosts: localhost
  tasks:
    - name: Build management docker image
      command: docker build -t babishan/management:1.0 $PROJECT_DIR/management
    - name: Build webservice docker image
      command: docker build -t babishan/webservice:1.0 $PROJECT_DIR/webservice