- hosts: all
  name: Do something with instances
  user: ubuntu
  become: yes
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: /etc/ansible/key

  tasks:
    - name: Wait for production instances to become reachable over SSH
      wait_for_connection:
        delay: 60
        timeout: 600
    - name: Ping
      ping: