- name: Clean up
  hosts: all
  tasks:
    - name: Delete project directories
      command : rm -rfv management webservice
    - name: stop docker containers
      command: /bin/sh -c 'for f in `docker ps -a -q`; do docker stop $f; done'
    - name: remove docker containers
      command: /bin/sh -c 'for f in `docker ps -a -q`; do docker rm $f; done'