- name: Create a network
  hosts:  all
  tasks:
    - community.docker.docker_network:
        name: datasnapshot


#- name: Pull ubuntu base image
#  hosts:  localhost
#  tasks:
#    - name: pull
#      docker_image:
#        name: ubuntu:16.04
#        source: pull