- hosts: localhost
  name: Create AWS infrastructure with Terraforms
  vars:
    terraform_dir: ../terraform

  tasks:
    - name: Create AWS all instances with Terraform
      terraform:
        project_path: "{{ terraform_dir }}"
        state: present
        force_init: yes
      register: outputs

    - name: Add all instance public DNS to production host group
      add_host:
        name: "{{ item }}"
        groups: production
      loop: "{{ outputs.outputs.production.value }}"

    - name: Add all instance public DNS to development host group
      add_host:
        name: "{{ item }}"
        groups: development
      loop: "{{ outputs.outputs.production.value }}"