- hosts: localhost
  name: Create AWS infrastructure with Terraforms
  vars:
    terraform_dir: ../terraform

  tasks:
    - name: Create AWS all instances with Terraform
      terraform:
        project_path: "{{ terraform_dir }}"
        state: present
        force_init: yes
      register: outputs

    - name: Add all instance public DNS to production host group
      add_host:
        name: "{{ item }}"
        groups: production
      loop: "{{ outputs.outputs.production.value }}"

    - name: Add all instance public DNS to development host group
      add_host:
        name: "{{ item }}"
        groups: development
      loop: "{{ outputs.outputs.production.value }}"

- hosts: production
  name: Do something with instances
  user: ubuntu
  become: yes
  gather_facts: false
  vars:
    ansible_ssh_private_key_file: /etc/ansible/key
  vars_prompt:
    - name: ssh add
      prompt: "Are you sure you want to continue connecting (yes/no/[fingerprint])?"
      default: yes
  tasks:
#    - name: Wait for production instances to become reachable over SSH
#      wait_for_connection:
#        delay: 60
#        timeout: 600
    - name: wait
      command: ssh -vvv -tt -o 'IdentityFile="/etc/ansible/key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="ubuntu"' -o ConnectTimeout=10 ec2-18-197-171-181.eu-central-1.compute.amazonaws.com '/bin/sh -c '"'"'echo ~ubuntu && sleep 0'"'"''
#    - name: Ping
#      ping: