- name: Ansible equivalent of docker-compose up
  hosts: localhost
  tasks:
    - command: ansible-playbook create_docker_network.yml
    - command: ansible-playbook build_docker_images.yml
    - command: ansible-playbook start_database_server.yml
    - command: ansible-playbook start_eureka_server.yml
    - command: ansible-playbook start_development_service.yml
    - command: ansible-playbook start_production_service.yml
    - command: ansible-playbook run_validator.yml