- name: dev validator
  hosts: localhost
  connection: local
  tasks:
   - name: Wait for the  service to be up
     command: sleep 30
   - name: validate eureka server
     uri:
       url: http://localhost:8761
       return_content: yes
     register: eureka
     failed_when: "'Instances currently registered with Eureka' not in eureka.content"
   - name: validate dev webservice
     uri:
       url: http://localhost:8081/login
       return_content: yes
     register: devservice
     failed_when: "'Please sign in' not in devservice.content"