- name: prod validator
  hosts: all
  connection: local
  tasks:
    - name: Wait for the  service to be up
      command: sleep 30
   - name: validate eureka server
     uri:
       url: http://localhost:8761
       return_content: yes
     register: eureka
     failed_when: "'Instances currently registered with Eureka' not in eureka.content"
   - name: validate webservice
     uri:
       url: http://localhost:8080/login
       return_content: yes
     register: service
     failed_when: "'Please sign in' not in service.content"